---
title: "FRCsignatures"
author: "A.DeMartin"
date: "2025-08-18"
output:
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

#### load packages
```{r load packages}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(here)
```

#### load merged object allFb
```{r}
## load object merged allFb naive and d4
basedir <- here()
fileNam <- paste0(basedir, "/data/merged_allFb_naiveANDd4_seurat.rds")
seuratFb <- readRDS(fileNam)
```

#### subset wt
```{r}
table(seuratFb$cond2)
seuratwt <- subset(seuratFb, cond2 == "WT")
table(seuratwt$cond2)

seuratFb <- seuratwt
```

#### exclude glial cells
```{r}
## filter glial cells
table(seuratFb$clustername)
seuratFb_noglial <- subset(seuratFb, clustername == "Glial", invert = TRUE)
table(seuratFb_noglial$clustername)

seuratFb <- seuratFb_noglial
```

#### set color vectors 
```{r}
colcond2 <- c("#202547","#BE3144")
names(colcond2) <- c("WT", "cko")

colcond3 <- c("#B45B5C","#628395","#BF782D")
names(colcond3) <- c("infectedD4", "naive", "granulomaD4")

colclustername <- c("#355C7D", "#8E9B97","#99B898","#E84A5F","#0F1F38","#F8B195","#727077","#FF847C","#C06C84")
names(colclustername) <- c("PdgfraloFb1" ,"PdgfraloFb2", "Trophocytes","PdgfraloFb3", "Telocytes","Myocytes", "Pdgfrahi", "PdgfraloFb4", "Thy1Fb")
```

#### counts
```{r}
table(seuratFb_noglial$orig.ident)
table(seuratFb_noglial$cond3)
```

### dotplots
#### sel FRC genes 
```{r dotplots of sel FRC genes wt only}
genes <- data.frame(gene=rownames(seuratFb)) %>% 
  mutate(geneID=gsub("^.*\\.", "", gene))

selGenes <- data.frame(geneID=rev(c("Ccl19", "Ccl21a", "Ccl2", "Il7", "Tnfsf11", "Clu", "Kitl", "Ltbr", "Irf7"))) %>% left_join(., genes, by="geneID")

DotPlot(seuratFb, features = selGenes, group.by= "cond3") + RotatedAxis() + scale_color_viridis(option="E") + coord_flip()
DotPlot(seuratFb, features = selGenes, group.by= "cond3") + RotatedAxis() + scale_color_viridis(option="E") 
DotPlot(seuratFb, features = selGenes, group.by= "cond3") + RotatedAxis() + scale_color_viridis(option="F") + coord_flip()
```

### signature umap
```{r convert to sce}
## convert seurat object to sce object
Idents(seuratFb) <- seuratFb$cond3
sce <- as.SingleCellExperiment(seuratFb)
genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582", "#b2183c", "#85122d"))

## subset naive and convert to sce
seuratFbnaive <- subset(seuratFb, cond3 == "naive")
DimPlot(seuratFbnaive, reduction= "umap", cols = colcond3) 
sceFbnaive <- as.SingleCellExperiment(seuratFbnaive)

## subset SI and convert to sce
seuratFbinf <- subset(seuratFb, cond3 == "infectedD4")
DimPlot(seuratFbinf, reduction= "umap", cols = colcond3) 
sceFbinf <- as.SingleCellExperiment(seuratFbinf)

## subset Gran and convert to sce
seuratFbgran <- subset(seuratFb, cond3 == "granulomaD4")
DimPlot(seuratFbgran, reduction= "umap", cols = colcond3) 
sceFbgran <- as.SingleCellExperiment(seuratFbgran)
```

#### FRC signature
```{r umap FRC signature}
selFRCgenes <- c("Ccl19", "Ccl21a", "Ccl2", "Il7", "Tnfsf11", "Clu", "Kitl", "Ltbr", "Irf7")

## make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% selFRCgenes)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceSub$sign2[which(sceSub$sign > 1)] <- 1
## check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

## make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 1)] <- 1
## check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

## make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 1)] <- 1
## check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

## make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 1)] <- 1
## check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

#### session info
```{r date and session info}
date()
sessionInfo()
```
