---
title: "GranulomaMph"
author: "A.DeMartin"
date: "2025-08-20"
output:
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

#### load packages
```{r load packages}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(here)
```

#### load merged file granuloma
```{r load merged file granuloma}
basedir <- here()
fileNam <- paste0(basedir, "/data/merged_allgranuloma_wofilter_seurat_wocl21.rds")
seurat <- readRDS(fileNam)
```

#### set color vectors
```{r set color vectors}
## col clustername
colclustername <- c("#355C7D","#B1746FFF","#202547","#B09C85", "#4e5a4c","#53354A","#2A363B","#8491B4FF","#00A087FF","#DC9989","#84ad83", "#628395","#D33B44","#779d8d","#727077","#868686FF","#F8B195","#FF847C","#725663FF","#904D39","#91D1C2")
names(colclustername) <- c("PdgfraloFb1","Mph1", "CD8Tcell1","Neut", "IgABcell1", "LEC", "Telocytes", "DC", "CD4Tcell/ILC2", "Mph2",  "NKcell", "CD8Tcell2", "Mph3", "Trophocytes", "PdgfrahiFb", "IgABcell2", "Myocytes", "PdgfraloFb2", "IgDBcell", "Glial", "ICC")

## col cond2
colcond2 <- c("#202547","#BE3144")
names(colcond2) <- c("WT", "cko")
```

### subset Mph
```{r subset mph}
seuratMph <- subset(seurat, cluster_name %in% c("Mph1","Mph2","Mph3"))
Idents(seuratMph) <- seuratMph$cluster_name
levels(seuratMph)
DimPlot(seuratMph, reduction = "umap", cols = colclustername) 
```

#### abundances Mph
```{r relative abundance mph}
## make count list
datList <- NULL
for(con in unique(seuratMph$cond2)){
  seuratSub <- subset(seuratMph, cond2==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$cluster_name)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(cond2=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

ordXcond2 <- c("WT", "cko")

## plot abundance
ggbarplot(dat_all, x= "cond2", y= "percent", fill = "Var1", legend = "right", legend.titel = "cluster_name", ylab = "frequency", palette = colclustername, order = ordXcond2) + theme(legend.position = "null")
```

#### Mph1 vs Mph3
```{r filter mph1 and mph3}
seuratMph1and3 <- subset(seurat, cluster_name %in% c("Mph1","Mph3"))
Idents(seuratMph1and3) <- seuratMph1and3$cluster_name
levels(seuratMph1and3)
```

#### DE genes Mph vs Mph3
```{r DE genes mph1 vs mph3}
Idents(seuratMph1and3) <- seuratMph1and3$cluster_name
levels(seuratMph1and3)
DEGenesMph1and3 <- FindAllMarkers(seuratMph1and3, only.pos=T, logfc.threshold = 0.2) %>% filter(p_val_adj < 0.01) 
```

#### scatterplot DE genes Mph1 vs Mph3
```{r scatter plot DEgenesMph1vsMph3, fig.height=15, fig.width=20}
## table with expression levels of all genes
allID <- seuratMph1and3
Idents(allID) <- allID$cluster_name
avg.allID <- AverageExpression(allID, group.by = "cluster_name")
avg.allID <- data.frame(log1p(avg.allID$RNA)) %>% 
  rownames_to_column(var="gene")

## table with genes of a certain expression frequency
GeneFreq <- as.data.frame(GetAssayData(allID, assay = "RNA", slot = "data")) %>%
  tibble::rownames_to_column(var="gene") %>% mutate(count=rowSums(.!=0)-1) %>%
  mutate(countFreq=count/ncol(allID)) %>%
  dplyr::select(gene, count, countFreq) %>%
  dplyr::filter(countFreq>=0.02)

## table with DEGenes to labeel - avg_log2FC > 1.5 and p_val_adj < 1e-100
genes.to.label <- DEGenesMph1and3 %>% group_by(.,cluster) %>%
  dplyr::filter(p_val_adj < 1e-100) %>% dplyr::filter(avg_log2FC > 1.5) %>% mutate(labelNam=gsub("^.*\\.","",gene)) 
  
avg.allID <- avg.allID %>% mutate(labelNam=gsub("^.*\\.","",gene)) %>% 
  mutate(colourGrp=ifelse(gene %in% genes.to.label$gene, "lab", 
                          ifelse(gene %in% DEGenesMph1and3$gene, "sig", "notSig"))) %>% dplyr::filter(gene%in%GeneFreq$gene)

p_allID <- ggscatter(avg.allID, x="Mph1", y="Mph3",
                     color = "colourGrp",
                     palette = c("#B2182B", "#808080", "#2166AC"),
                     label= "labelNam",
                     label.select = genes.to.label$labelNam,
                     repel = T,
                     label.rectangle = F,
                     xlab = "Mph1",
                     ylab = "Mph3",
                     font.label = c("10", "plain","black"),
                     size=2,)
p_allID
```

#### GSEA Mph1
```{r GSEA Mph1, fig.height=14, fig.width=12}
DEGenesMph1 <- dplyr::filter(DEGenesMph1and3, cluster == "Mph1")
DEGenesMph1 <- DEGenesMph1 %>% rownames_to_column(., var = "long") %>%
  mutate(gene=gsub("^.*\\.", "", long))  %>%
  mutate(EnsID=gsub("\\..*","", long))

## GSEA Mph1
egoMph1 <- enrichGO(gene = unique(DEGenesMph1$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoMph1 <- setReadable(egoMph1, OrgDb = org.Mm.eg.db)
dotplot(egoMph1, showCategory=30)
```

#### GSEA Mph3
```{r GSEA Mph3, fig.height=14, fig.width=12}
DEGenesMph3 <- dplyr::filter(DEGenesMph1and3, cluster == "Mph3")
DEGenesMph3 <- DEGenesMph3 %>% rownames_to_column(., var = "long") %>%
  mutate(gene=gsub("^.*\\.", "", long))  %>%
  mutate(EnsID=gsub("\\..*","", long))

## GSEA Mph3
egoMph3 <- enrichGO(gene = unique(DEGenesMph3$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoMph3 <- setReadable(egoMph3, OrgDb = org.Mm.eg.db)
dotplot(egoMph3, showCategory=30)
```

#### barplot GSEA
```{r barplot GSEA}
## selected pathways
selMph1 <- c("GO:0045088","GO:0019221", "GO:0032640", "GO:0034341")
egoMph1_fil <- egoMph1%>% filter(egoMph1@result$ID %in% selMph1)

egoMph1_fil_2 <- pairwise_termsim(egoMph1_fil)
## make ggbarplot
p <- ggbarplot(egoMph1_fil_2@result, x = "Description", y = "Count", fill = "#B1746FFF", color="#B1746FFF", sort.val = "asc", orientation = "horizontal")
p
```

#### CD45 positive (immmune cells)
```{r}
## subset CD45+ cells
seuratCD45pos <- subset(seurat, cluster_name %in% c("CD8Tcell1","CD8Tcell2","NKcell","CD4Tcell/ILC2","Neut","Mph1","Mph2","Mph3","DC","IgABcell1","IgABcell2","IgDBcell"))
table(seuratCD45pos$cluster_name)
```
#### average heatmap Ccr1 Ccr2 Ccr5
```{r avg heatmap Ccr1 Ccr2 Ccr5, fig.height=8, fig.width=5}
Idents(seuratCD45pos) <- seuratCD45pos$cluster_name
seurat <- seuratCD45pos
levels(seurat)
avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  selGenes <- selGenes$gene
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colclustername)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

genesPlot <- data.frame(gene=c("Ccr1", "Ccr2" ,"Ccr5"))

colVec <- colclustername

avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)
```

#### average heatmap cytokine-mediated signaling pathway
```{r avg heatmap cytokine-mediated signaling pathway, fig.height=8, fig.width=5}
Idents(seuratMph) <- seuratMph$cluster_name
seurat <- seuratMph
levels(seurat)
avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  selGenes <- selGenes$gene
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colclustername)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

genesPlot <- data.frame(gene=c("Osm", "Il1b", "Ccl6", "Ccl9", "Ccl2", "Ccr1", "Cxcl2", "Ccl7", "Ccl4", "Il1rn","Myd88", "Cxcl10", "Cxcl3"))

colVec <- colclustername

avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)
```

### violin plots Mph
#### Mph subsets
```{r violin plot Mph subset}
Idents(seuratMph) <- seuratMph$cluster_name
VlnPlot(object=seuratMph, features = "ENSMUSG00000058755.Osm", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000027398.Il1b", pt.size = 0, cols = colclustername) + theme(legend.position = "none")

VlnPlot(object=seuratMph, features = "ENSMUSG00000018927.Ccl6", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000019122.Ccl9", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000035385.Ccl2", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000025804.Ccr1", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000058427.Cxcl2", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000035373.Ccl7", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000018930.Ccl4", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000026981.Il1rn", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000032508.Myd88", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000034855.Cxcl10", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000029379.Cxcl3", pt.size = 0, cols = colclustername) + theme(legend.position = "none")
```

#### cond
```{r violin plot cond}
Idents(seuratMph) <- seuratMph$orig.ident
VlnPlot(object=seuratMph, features = "ENSMUSG00000058755.Osm", pt.size = 0, cols = colcond2, split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000027398.Il1b", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")

VlnPlot(object=seuratMph, features = "ENSMUSG00000018927.Ccl6", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000019122.Ccl9", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000035385.Ccl2", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000025804.Ccr1", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000058427.Cxcl2", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000035373.Ccl7", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000018930.Ccl4", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000026981.Il1rn", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000032508.Myd88", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000034855.Cxcl10", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
VlnPlot(object=seuratMph, features = "ENSMUSG00000029379.Cxcl3", pt.size = 0, cols = colcond2,split.by = "cond2", split.plot = "TRUE") + theme(legend.position = "none")
```

#### session info
```{r date and session info}
date()
sessionInfo()
```
